[package]
name = "j-wordle"
version = "0.1.0"
description = "Wordle TUI"
authors = ["jobin_nelson <jobinnelson369@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
derive_more = { version = "2.1.1", features = ["from"] }
indoc = "2.0.8"
rand = "0.10.3"
ratatui = "0.30.2"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
